### DISCUSSION TITLE
Scikit-build Community Meeting Notes #9: 2023-07-21

### DISCUSSION THREAD

**Discussion by thewtex** [scikit-build/scikit-build#1015] [Community meeting notes]
## Agenda 

* Review [slides](https://docs.google.com/presentation/d/1p9N3VKLXFCOyrHTIomYCf8lk0BN_0EBE6j8jMikGU7I/edit#slide=id.p) from @henryiii.
* Round table

## Attending

- Matt McCormick
- Henry Scheiner
- Jean-Christophe Fillion-Robin

## Discussion

- A few updates, a lot of progress, new projects were adopted at the SciPy conference
- `itk-5.4rc1` built with latest scikit-build classic now 

### Slides review notes

- Continue to improve cross-compling support
    - FindPython does not support cross-compiling very well yet
- CMake component support in progress
    - supply components in pyproject.yaml
    - build targets
        - multiple
        - cmake --build <target1> <target2>
- sdist normalization
    - always lower case, underscores in sdist filename output
- dynamic-metadata
    - now a package (at SciPy conf)
    - redesign targetted for 0.5
    - regex plugin for extracting metadata like hatch
    - develop a plugin as an example to get the package version from the CMake cache? 
    - minimum version plugin 
    - generate package dependencies during build
        - need to update packaging standards so we can have static + additional dynamic dependencies
    - hacking build-system.requires, dynamic-metadata packages to add wheels to bring in
        - build-time sdks
        - utility cmake modules
            - relevant test: https://github.com/scikit-build/scikit-build-core/tree/main/tests/packages/custom_cmake
- Python 2.7 support
    - Will be able to use the wheel
    - Be able to build the wheel?
- [CPython Cross-compiling for scikit-build, meson-python](https://discuss.python.org/t/pep-720-cross-compiling-python-packages/29988)
- [Slides from SciPy Projects Tools Updates](https://docs.google.com/presentation/d/1_nIpJUlnoEWg2-jfzwgGv6ijqNX1sKvOm-b3cmKFLUs/edit#slide=id.p)

### Recording and Transcript

- NA
    
    
### Example for dynamic-metadata configuration with plugin dependencies
    
```toml
[build-system]
requires = ["scikit-build-core", "setuptools-scm", "dynamic-metadata-regex"]

[project]
dynamic = ["version", "description", "dependencies"]

dependencies = ["numpy"]

[tool.dynamic-metadata]
version.provider = "setuptools_scm"
description.provider = "dynamic_metadata_regex"
description.regex = "(*.)"
```

    
* Having multiple line in a table is only supported in toml 2.1 and above

```toml
description = {
    provider = "dynamic_metadata_regex",
    regex = "(*.)"
}
```
