### ISSUE TITLE
Support for pyproject.toml in Pip 10

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build#312]
Pip 10.0.0b1 was released, with support for `pyproject.toml`. This allows a project to specify that it needs `scikit-build` in the setup phase, allowing for the first time a simple "pip install package" for a scikit-build package. `pyproject.tomls` should be added to the examples in tests and documtentation.

On a related note, `cmake` could be added as a dependency as well, but since a user may have cmake, that's probably better in `setup_requires` or maybe not at all. If scikit-build could gain a new `require_cmake_version` argument, which would then check for the cmake command and ask it's version, then add the python 'cmake' as a requirement if this does not pass, that might be ideal.

**Comment by henryiii** [comment]
By the way, https://github.com/henryiii/skbuild-hello-cpp/blob/master/pyproject.toml is an example of such a file.

**Comment by jcfr** [comment]
xref #313

**Comment by jcfr** [comment]
The basic usage section has been updated accordingly.

See http://scikit-build.readthedocs.io/en/latest/usage.html#example-of-setup-py-cmakelists-txt-and-pyproject-toml

**Comment by thewtex** [comment]
@jcfr we can close this?

**Comment by jcfr** [comment]
Not yet:
* [ ] add test using `pyproject.toml`

**Comment by stefansjs** [comment]
FYI there's a relationship between `build-system.requires` and `setup_requires` that's a little less than obvious. For PEP517 builds I noticed that I needed to _already_ have my dependencies installed by declaring them in pyproject.toml, and then setuptools will fail if the setup_requires criteria don't already match the environment. 

More specifically, yes you need cmake in `build-system.requires`. Here's an example of my pyproject.toml and the relevant chunk of setup.py:

```toml
[build-system]
requires = [
    "setuptools>=50.0",
    "wheel",
    "scikit-build",
    "cmake==3.14.4",
    "Cython==0.25.1; python_version>='2.7' and python_version<='3.6'",
    "Cython==0.29.19; python_version>='3.7'",
    "cysignals==1.6.5",
    "pycodestyle==2.5.0"  # This is required in order to install avro-python3
]
```

```python
        setup_requires=[
            'scikit-build',
            'cmake==3.14.4',
            # I tried specifying cython versions with environment markers, but setuptools doesn't respect them.
            # Relying on pyproject.toml to correctly install the right cython for the right python interpreter
            "Cython>=0.25.1",  # This version doesn't work on 3.7+
            "Cython<=0.29.19",
            'cysignals==1.6.5',
            'pycodestyle==2.5.0',  # This is required in order to install avro-python3
        ],
```

(I had issues with cython). It was interesting that I could use all the environment markers in pyproject.toml, but setup.py just needed me to list the same requirement multiple times.

Just wanted to share my experience so that others don't go through the same painful process I did to figure it out.
