### ISSUE TITLE
Create a scikit-ci project

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#46]
As originally commented in https://github.com/scikit-build/scikit-build/issues/34#issuecomment-229844713 , a dedicated project could be created to facilitate the reuse of the ci/appveyor/driver.py script developed by @opadron 

In its initial version, the package would provide the driver script allowing to setup the environment on appveyor.

**Comment by opadron** [comment]
I think this is definitely a worthwhile task, but I wonder how much overlap we'd have with something like conda forge?  Do we want to make something on our own?  Should we try to repurpose their efforts?

**Comment by jcfr** [comment]
The original motivation is not to create something like conda forge. Instead, this project would only contain helper scripts like the `ci/appveyor/driver.py`. Instead conda forge could depends on this package.

May be `scikit-ci-utils` or  `scikit-appveyor` would be a better name then.

**Comment by opadron** [comment]
I'm glad to look into this, but I lack the permissions necessary to create a new repository under the scikit-build organization.

**Comment by opadron** [comment]
Also, there is the question of license.  To what entity do we attribute copyright, and under what license do we distribute?

**Comment by jcfr** [comment]
There is now a new project: https://github.com/scikit-build/scikit-ci


Since we wanted to keep the `ci` folder, and that `git subtree` could not (easily) be used to do so, history has been instead filtered/extracted from scikit-build using  `dockgit-rocket-filter`

[jcfr/dockgit-rocket-filter](https://github.com/jcfr/dockgit-rocket-filter) which is a dockerized version of [GitRocketFilter](https://github.com/xoofx/GitRocketFilter).


For reference, here were the steps:

```
git clone git@github.com:scikit-build/scikit-build.git scikit-ci
cd scikit-ci

# Extract
git branch -M oldmaster
git-rocket-filter --branch master --keep ci
git branch -D oldmaster

# Clean
git remote remove origin
git tag -l | xargs git tag -d
git reflog expire --expire=now --all
git gc --aggressive --prune=now

# Add README and LICENSE

# Publish
git remote add origin git@github.com:scikit-build/scikit-ci.git
git push origin master
```

**Comment by jcfr** [comment]
The infrastructure to work with `scikit-ci.yml` is getting ready.

See https://github.com/scikit-build/scikit-ci/tree/scikit-ci-config

The last things to implement is the support for `$<ENVVAR>` .. a platform independent way (specific to scikit-ci) of getting the value of environment variable.

It will allow to do things like this:

```
before_install:

  appveyor:
    environment:
      RUN_ENV: ci/appveyor/run-with-visual-studio.cmd
    commands:
      - python ci/appveyor/patch_vs2008.py
      - python ci/appveyor/install_visual_studio_wrapper.py

[...]

install:

  commands:
    - python ci/install_cmake.py 3.6.2
    - $<RUN_ENV> python -m pip install --disable-pip-version-check --upgrade pip
    - $<RUN_ENV> python -m pip install -r requirements.txt
    - $<RUN_ENV> python -m pip install -r requirements-dev.txt
[...]
```
