### ISSUE TITLE
Windows: error does result in exit 1?

### ISSUE THREAD

**Issue by tdegeus** [scikit-build/scikit-build#698]
My build error on Windows does not lead to a CI failure : https://github.com/tdegeus/FrictionQPotSpringBlock/runs/5992549310?check_suite_focus=true

**Comment by henryiii** [comment]
From a quick look, it seems the thing inside the SystemExit / sys.exit call is not an int like it should be.

**Comment by tdegeus** [comment]
Indeed. I have the impression that there is a `try` `except` somewhere that prints something under `except` but that does not throw or exit in the end. The thing is, I cannot to easily estimate where that happens, as, because of the same reason there is not traceback (in general that is a bit of problem when `sys.exit` is used over `raise`).

**Comment by henryiii** [comment]
You are replacing the bash command. The exit code is 1, but the following command `rm` succeeds, so the command passes. If you use the default shell, that errors immediately, but not if you replace the shell. You need to pass `-e` to bash.

**Comment by tdegeus** [comment]
Thanks. So you say it would fail with 
```yaml
    defaults:
       run:
         shell: bash -e -l {0}
```
It just surprises me that I don't think I have had this problem before.

**Comment by tdegeus** [comment]
I hear what you say, but now that I'm paying extra attention: in another repo I have 
```yaml
    - name: Run tests
      working-directory: tests
      run: |
        python foo.py
        python bar.py
```
In this case the CI fails when `foo.py` fails. `bar.py` is not even ran. True that happens on Ubuntu.
